In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('US_honey_dataset_updated.csv')

In [4]:
df.head()

,Unnamed: 0,state,colonies_number,yield_per_colony,production,stocks,average_price,value_of_production,year
0,0,Alabama,16000,58,928000,28000,62.0,575000,1995
1,1,Arizona,52000,79,4108000,986000,68.0,2793000,1995
2,2,Arkansas,50000,60,3000000,900000,64.0,1920000,1995
3,3,California,420000,93,39060000,4687000,60.0,23436000,1995
4,4,Colorado,45000,60,2700000,1404000,68.0,1836000,1995

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1115 entries, 0 to 1114
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           1115 non-null   int64
 1   state                1115 non-null   str
 2   colonies_number      1115 non-null   int64
 3   yield_per_colony     1115 non-null   int64
 4   production           1115 non-null   int64
 5   stocks               1115 non-null   int64
 6   average_price        1115 non-null   float64
 7   value_of_production  1115 non-null   int64
 8   year                 1115 non-null   int64
dtypes: float64(1), int64(7), str(1)
memory usage: 78.5 KB

In [6]:
df.describe()

,Unnamed: 0,colonies_number,yield_per_colony,production,stocks,average_price,value_of_production,year
count,1115.00000,1115.000000,1115.000000,1.115000e+03,1.115000e+03,1115.000000,1.115000e+03,1115.000000
mean,557.00000,62438.565022,59.743498,2.851268e+06,1.172625e+06,140.623076,5.667412e+06,2007.740807
std,322.01708,92648.175955,19.940500,5.561202e+06,2.049556e+06,107.011544,9.459460e+06,7.823002
min,0.00000,2000.000000,19.000000,1.200000e+04,9.000000e+03,1.300000,1.060000e+05,1995.000000
25%,278.50000,9000.000000,45.000000,2.460000e+05,1.125000e+05,70.000000,1.008000e+06,2001.000000
50%,557.00000,26000.000000,57.000000,8.280000e+05,3.700000e+05,128.000000,2.281000e+06,2008.000000
75%,835.50000,69000.000000,71.000000,2.700000e+06,1.253500e+06,193.000000,5.704000e+06,2015.000000
max,1114.00000,550000.000000,155.000000,3.906000e+07,1.354500e+07,874.000000,8.385900e+07,2021.000000

In [7]:
for i in df['state'].unique():
    print(i)

Alabama
Arizona
Arkansas
California
Colorado
Florida
Georgia
Hawaii
Idaho
Illinois
Indiana
Iowa
Kansas
Kentucky
Louisiana
Maine
Maryland
Michigan
Minnesota
Mississippi
Missouri
Montana
Nebraska
Nevada
NewJersey
NewMexico
NewYork
NorthCarolina
NorthDakota
Ohio
Oklahoma
Oregon
Pennsylvania
SouthCarolina
SouthDakota
Tennessee
Texas
Utah
Vermont
Virginia
Washington
WestVirginia
Wisconsin
Wyoming

In [8]:
df.groupby('state')['production'].sum()

state
Alabama           14467000
Arizona           38844000
Arkansas          51846000
California       423876000
Colorado          32660000
Florida          280934000
Georgia           57426000
Hawaii            15420000
Idaho             87188000
Illinois           9864000
Indiana            9686000
Iowa              48607000
Kansas            14138000
Kentucky           3224000
Louisiana         60568000
Maine              4762000
Maryland           1975000
Michigan         101063000
Minnesota        176581000
Mississippi       21235000
Missouri          17904000
Montana          197173000
Nebraska          63655000
Nevada             7399000
NewJersey          6913000
NewMexico         10082000
NewYork           78444000
NorthCarolina      8909000
NorthDakota      513742000
Ohio              22485000
Oklahoma           2055000
Oregon            43789000
Pennsylvania      21370000
SouthCarolina      2823000
SouthDakota      355726000
Tennessee          6857000
Texas            129441000
Utah              20369000
Vermont            7032000
Virginia           5153000
Washington        53238000
WestVirginia       6411000
Wisconsin         99909000
Wyoming           43921000
Name: production, dtype: int64

In [9]:
df['state'].value_counts()

state
Alabama          27
Arizona          27
Arkansas         27
California       27
Colorado         27
Florida          27
Georgia          27
Hawaii           27
Idaho            27
Illinois         27
Indiana          27
Iowa             27
Kansas           27
Louisiana        27
Maine            27
Michigan         27
Minnesota        27
Mississippi      27
Missouri         27
Montana          27
Nebraska         27
NewJersey        27
NewYork          27
NorthCarolina    27
NorthDakota      27
Ohio             27
Oregon           27
Pennsylvania     27
SouthDakota      27
Tennessee        27
Texas            27
Utah             27
Vermont          27
Virginia         27
Washington       27
WestVirginia     27
Wisconsin        27
Wyoming          27
Kentucky         26
NewMexico        18
Nevada           15
SouthCarolina    12
Maryland          9
Oklahoma          9
Name: count, dtype: int64

In [11]:
pd.set_option('display.float_format','{:.0f}'.format)

In [12]:
df.groupby('state')['production'].agg(['sum', 'mean', 'max', 'min'])

                     sum     mean       max      min
state
Alabama         14467000   535815   1248000    13000
Arizona         38844000  1438667   4108000    97000
Arkansas        51846000  1920222   5655000    66000
California     423876000 15699111  39060000  1485000
Colorado        32660000  1209630   2700000   200000
Florida        280934000 10404963  25200000   529000
Georgia         57426000  2126889   5100000   152000
Hawaii          15420000   571111   1314000    18000
Idaho           87188000  3229185   7680000   270000
Illinois         9864000   365333    814000    77000
Indiana          9686000   358741    828000    82000
Iowa            48607000  1800259   3900000   463000
Kansas          14138000   523630   1207000    39000
Kentucky         3224000   124000    280000    12000
Louisiana       60568000  2243259   5472000   141000
Maine            4762000   176370    495000    17000
Maryland         1975000   219444    308000    84000
Michigan       101063000  3743074   8924000   768000
Minnesota      176581000  6540037  13530000   285000
Mississippi     21235000   786481   1575000    39000
Missouri        17904000   663111   1848000    30000
Montana        197173000  7302704  14030000  1934000
Nebraska        63655000  2357593   4875000   223000
Nevada           7399000   493267    854000   261000
NewJersey        6913000   256037    539000    34000
NewMexico       10082000   560111   1235000    99000
NewYork         78444000  2905333   5880000   665000
NorthCarolina    8909000   329963    714000    63000
NorthDakota    513742000 19027481  35100000  2266000
Ohio            22485000   832778   1760000   228000
Oklahoma         2055000   228333    380000   141000
Oregon          43789000  1621815   3245000   456000
Pennsylvania    21370000   791481   1620000   177000
SouthCarolina    2823000   235250    810000    15000
SouthDakota    355726000 13175037  28435000  3604000
Tennessee        6857000   253963    549000    54000
Texas          129441000  4794111   9964000   384000
Utah            20369000   754407   1740000    67000
Vermont          7032000   260444    623000    43000
Virginia         5153000   190852    468000    21000
Washington      53238000  1971778   3540000   412000
WestVirginia     6411000   237444    590000    32000
Wisconsin       99909000  3700333   8099000   683000
Wyoming         43921000  1626704   3627000   146000

In [16]:
df.groupby('state').agg({
    'production' : 'sum',
    'average_price' : 'mean',
    'value_of_production' : 'mean'
})

               production  average_price  value_of_production
state
Alabama          14467000            150              1061778
Arizona          38844000            110              2213778
Arkansas         51846000            106              2732630
California      423876000            109             24221556
Colorado         32660000            119              2364593
Florida         280934000            110             18876667
Georgia          57426000            121              5405370
Hawaii           15420000            138              1847704
Idaho            87188000            106              5168000
Illinois          9864000            216              1362296
Indiana           9686000            155               913259
Iowa             48607000            124              3243074
Kansas           14138000            147              1035926
Kentucky          3224000            202               593346
Louisiana        60568000            103              4800037
Maine             4762000            174               734889
Maryland          1975000            146               303889
Michigan        101063000            123              8068185
Minnesota       176581000            107             11498593
Mississippi      21235000            103              2195000
Missouri         17904000            146              1198963
Montana         197173000            110             15057889
Nebraska         63655000            111              3962889
Nevada            7399000            205               968000
NewJersey         6913000            195              1044481
NewMexico        10082000            122               613833
NewYork          78444000            136              6589667
NorthCarolina     8909000            205              1431296
NorthDakota     513742000            106             43934037
Ohio             22485000            164              2208778
Oklahoma          2055000            134               290889
Oregon           43789000            119              3781815
Pennsylvania     21370000            153              2042704
SouthCarolina     2823000            176              2184833
SouthDakota     355726000            107             22929444
Tennessee         6857000            197              1010222
Texas           129441000            110             10545185
Utah             20369000            111              1487296
Vermont           7032000            174               706815
Virginia          5153000            238               775000
Washington       53238000            119              4437889
WestVirginia      6411000            191               692037
Wisconsin        99909000            126              6534889
Wyoming          43921000            108              3240815

In [20]:
report = df.groupby('state').agg(
    total_production = ('production', 'sum'),
    average_price = ('production', 'mean'),
    max_production = ('production', 'max')
)

In [21]:
report.total_production

state
Alabama           14467000
Arizona           38844000
Arkansas          51846000
California       423876000
Colorado          32660000
Florida          280934000
Georgia           57426000
Hawaii            15420000
Idaho             87188000
Illinois           9864000
Indiana            9686000
Iowa              48607000
Kansas            14138000
Kentucky           3224000
Louisiana         60568000
Maine              4762000
Maryland           1975000
Michigan         101063000
Minnesota        176581000
Mississippi       21235000
Missouri          17904000
Montana          197173000
Nebraska          63655000
Nevada             7399000
NewJersey          6913000
NewMexico         10082000
NewYork           78444000
NorthCarolina      8909000
NorthDakota      513742000
Ohio              22485000
Oklahoma           2055000
Oregon            43789000
Pennsylvania      21370000
SouthCarolina      2823000
SouthDakota      355726000
Tennessee          6857000
Texas            129441000
Utah              20369000
Vermont            7032000
Virginia           5153000
Washington        53238000
WestVirginia       6411000
Wisconsin         99909000
Wyoming           43921000
Name: total_production, dtype: int64

In [22]:
df.groupby('state').agg({
    'production': ['sum', 'mean', 'max', 'min'],
    'average_price': ['sum', 'mean', 'max', 'min']
})

              production                             average_price           \
                     sum     mean       max      min           sum mean max
state
Alabama         14467000   535815   1248000    13000          4058  150 383
Arizona         38844000  1438667   4108000    97000          2979  110 203
Arkansas        51846000  1920222   5655000    66000          2870  106 206
California     423876000 15699111  39060000  1485000          2954  109 216
Colorado        32660000  1209630   2700000   200000          3201  119 226
Florida        280934000 10404963  25200000   529000          2968  110 243
Georgia         57426000  2126889   5100000   152000          3261  121 300
Hawaii          15420000   571111   1314000    18000          3719  138 415
Idaho           87188000  3229185   7680000   270000          2870  106 203
Illinois         9864000   365333    814000    77000          5842  216 542
Indiana          9686000   358741    828000    82000          4183  155 361
Iowa            48607000  1800259   3900000   463000          3342  124 245
Kansas          14138000   523630   1207000    39000          3977  147 403
Kentucky         3224000   124000    280000    12000          5250  202 413
Louisiana       60568000  2243259   5472000   141000          2783  103 218
Maine            4762000   176370    495000    17000          4692  174 543
Maryland         1975000   219444    308000    84000          1310  146 191
Michigan       101063000  3743074   8924000   768000          3312  123 249
Minnesota      176581000  6540037  13530000   285000          2888  107 206
Mississippi     21235000   786481   1575000    39000          2777  103 240
Missouri        17904000   663111   1848000    30000          3942  146 370
Montana        197173000  7302704  14030000  1934000          2961  110 221
Nebraska        63655000  2357593   4875000   223000          3004  111 207
Nevada           7399000   493267    854000   261000          3068  205 360
NewJersey        6913000   256037    539000    34000          5263  195 874
NewMexico       10082000   560111   1235000    99000          2197  122 339
NewYork         78444000  2905333   5880000   665000          3664  136 319
NorthCarolina    8909000   329963    714000    63000          5540  205 478
NorthDakota    513742000 19027481  35100000  2266000          2863  106 204
Ohio            22485000   832778   1760000   228000          4417  164 393
Oklahoma         2055000   228333    380000   141000          1203  134 183
Oregon          43789000  1621815   3245000   456000          3221  119 243
Pennsylvania    21370000   791481   1620000   177000          4131  153 362
SouthCarolina    2823000   235250    810000    15000          2112  176 457
SouthDakota    355726000 13175037  28435000  3604000          2892  107 208
Tennessee        6857000   253963    549000    54000          5318  197 488
Texas          129441000  4794111   9964000   384000          2966  110 224
Utah            20369000   754407   1740000    67000          3003  111 213
Vermont          7032000   260444    623000    43000          4689  174 489
Virginia         5153000   190852    468000    21000          6420  238 585
Washington      53238000  1971778   3540000   412000          3208  119 261
WestVirginia     6411000   237444    590000    32000          5162  191 444
Wisconsin       99909000  3700333   8099000   683000          3411  126 282
Wyoming         43921000  1626704   3627000   146000          2904  108 211


              min
state
Alabama         3
Arizona         2
Arkansas        2
California      2
Colorado        2
Florida         2
Georgia         3
Hawaii          1
Idaho           2
Illinois        4
Indiana         4
Iowa            2
Kansas          2
Kentucky        5
Louisiana       2
Maine           3
Maryland      110
Michigan        2
Minnesota       2
Mississippi     2
Missouri        3
Montana         1
Nebraska        1
Nevada         96
NewJersey       3
NewMexico      65
NewYork         3
NorthCarolina   4
NorthDakota     1
Ohio            3
Oklahoma       91
Oregon          2
Pennsylvania    3
SouthCarolina   3
SouthDakota     2
Tennessee       4
Texas           2
Utah            2
Vermont         3
Virginia        6
Washington      2
WestVirginia    4
Wisconsin       3
Wyoming         1

In [25]:
df.groupby(['year', 'state'])['production'].sum().head(10)

year  state
1995  Alabama         928000
      Arizona        4108000
      Arkansas       3000000
      California    39060000
      Colorado       2700000
      Florida       19780000
      Georgia        4340000
      Hawaii         1032000
      Idaho          6000000
      Illinois        814000
Name: production, dtype: int64

In [27]:
df[(df['state'] == 'Alabama') & (df['year'] == 2012)]

,Unnamed: 0,state,colonies_number,yield_per_colony,production,stocks,average_price,value_of_production,year
716,716,Alabama,8000,54,65000,65000,247,1067000,2012

In [29]:
df[df['year'].between(2000, 2002) & (df['state'] == 'Alabama')]

,Unnamed: 0,state,colonies_number,yield_per_colony,production,stocks,average_price,value_of_production,year
217,217,Alabama,16000,78,1248000,187000,59,736000,2000
260,260,Alabama,14000,73,1022000,235000,71,726000,2001
303,303,Alabama,12000,86,1032000,103000,111,1146000,2002

In [32]:
df[df['year'].between(2001, 2005) & (df['state'] == 'Alabama')]['production'].sum()

np.int64(5022000)