In [1]:
import pandas as pd

In [3]:
df1 = pd.DataFrame({
    'name': ['rahul', 'sachin', 'virat'],
    'age': [30, 40, 35]
})

df2 = pd.DataFrame({
    'name': ['sheela', 'neha', 'priya'],
    'age': [25, 30, 28]
})

In [4]:
pd.concat([df1, df2]).reset_index(drop=True)

     name  age
0   rahul   30
1  sachin   40
2   virat   35
3  sheela   25
4    neha   30
5   priya   28

In [ ]:
df3 = pd.concat([df1, df2], axis=1).reset_index(drop=True)
df3

     name  age    name  age
0   rahul   30  sheela   25
1  sachin   40    neha   30
2   virat   35   priya   28

In [7]:
student = pd.DataFrame({
    'roll no': [1, 2, 3,4,5],
    'name': ['rahul', 'sachin', 'virat', 'sheela', 'neha']
})

In [9]:
marks = pd.DataFrame({
    'roll no': [1, 2, 3, 4, 7, 6],
    'marks': [80, 90, 85, 95, 70, 75]
})

In [10]:
pd.merge(student, marks, on='roll no')

   roll no    name  marks
0        1   rahul     80
1        2  sachin     90
2        3   virat     85
3        4  sheela     95

In [11]:
pd.merge(student, marks, on='roll no', how='left')

   roll no    name  marks
0        1   rahul   80.0
1        2  sachin   90.0
2        3   virat   85.0
3        4  sheela   95.0
4        5    neha    NaN

In [12]:
pd.merge(student, marks, on='roll no', how='right')

   roll no    name  marks
0        1   rahul     80
1        2  sachin     90
2        3   virat     85
3        4  sheela     95
4        7     NaN     70
5        6     NaN     75

In [14]:
pd.merge(student, marks, on='roll no', how='outer')

   roll no    name  marks
0        1   rahul   80.0
1        2  sachin   90.0
2        3   virat   85.0
3        4  sheela   95.0
4        5    neha    NaN
5        6     NaN   75.0
6        7     NaN   70.0