In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame([
    [22,33,44,55,66],
    [34,56,78,76,78]
                  ])

In [3]:
df

    0   1   2   3   4
0  22  33  44  55  66
1  34  56  78  76  78

In [4]:
df3 = pd.DataFrame({
    'English' : [34,43,45,56,66],
    'Science' : [43,34,56,65,67],
    'Maths' : [45,54,77,87,78]
})

In [5]:
df3

   English  Science  Maths
0       34       43     45
1       43       34     54
2       45       56     77
3       56       65     87
4       66       67     78

In [7]:
df3.index = ['abhi','aadarsh','aaditya','chandu chai wala','Somaya chandu ki ghar wali']

In [8]:
df3

                            English  Science  Maths
abhi                             34       43     45
aadarsh                          43       34     54
aaditya                          45       56     77
chandu chai wala                 56       65     87
Somaya chandu ki ghar wali       66       67     78

In [ ]:
# Transpose
df3.T

         abhi  aadarsh  aaditya  chandu chai wala  Somaya chandu ki ghar wali
English    34       43       45                56                          66
Science    43       34       56                65                          67
Maths      45       54       77                87                          78