In [139]:
import pandas as pd

In [140]:
df = pd.read_csv('large_messy_dataset_option2.csv')

In [141]:
df

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,0,riya,NaN,116530,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32.0,NaN,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,NaN,-10000,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,-3.0,-10000,Kolkata,riya8@gmail.com,2023/04/20
4,58,Karan,NaN,112349,Delhi,karan43@gmail.com,2023-01-15
...,...,...,...,...,...,...,...
295,11,karan,-3.0,Not Available,Mumbai,karan29@gmail.com,NaN
296,88,anjali,54.0,39808,Delhi,anjali43@gmail.com,2023/04/20
297,121,Simran,0.0,-10000,Kolkata,simran16@gmail.com,2023-01-15
298,298,Rohit,NaN,-10000,Mumbai,rohit11@gmail.com,15/02/2023
299,299,Aman,NaN,NaN,Kolkata,aman17@gmail.com,2023-01-15

In [142]:
df.CustomerID.sort_values(inplace=True)

In [143]:
df

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,0,riya,NaN,116530,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32.0,NaN,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,NaN,-10000,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,-3.0,-10000,Kolkata,riya8@gmail.com,2023/04/20
4,58,Karan,NaN,112349,Delhi,karan43@gmail.com,2023-01-15
...,...,...,...,...,...,...,...
295,11,karan,-3.0,Not Available,Mumbai,karan29@gmail.com,NaN
296,88,anjali,54.0,39808,Delhi,anjali43@gmail.com,2023/04/20
297,121,Simran,0.0,-10000,Kolkata,simran16@gmail.com,2023-01-15
298,298,Rohit,NaN,-10000,Mumbai,rohit11@gmail.com,15/02/2023
299,299,Aman,NaN,NaN,Kolkata,aman17@gmail.com,2023-01-15

In [144]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerID   300 non-null    int64
 1   Name         300 non-null    str
 2   Age          225 non-null    float64
 3   Salary       227 non-null    str
 4   City         251 non-null    str
 5   Email        300 non-null    str
 6   JoiningDate  234 non-null    str
dtypes: float64(1), int64(1), str(5)
memory usage: 16.5 KB

In [145]:
df.describe()

       CustomerID         Age
count  300.000000  225.000000
mean   114.746667   10.746667
std     80.658385   19.774009
min      0.000000   -3.000000
25%     45.750000   -3.000000
50%    101.000000    0.000000
75%    156.250000   25.000000
max    299.000000   59.000000

In [146]:
df.isnull().sum()

CustomerID      0
Name            0
Age            75
Salary         73
City           49
Email           0
JoiningDate    66
dtype: int64

In [147]:
df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')

In [148]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerID   300 non-null    int64
 1   Name         300 non-null    str
 2   Age          225 non-null    float64
 3   Salary       152 non-null    float64
 4   City         251 non-null    str
 5   Email        300 non-null    str
 6   JoiningDate  234 non-null    str
dtypes: float64(2), int64(1), str(4)
memory usage: 16.5 KB

In [149]:
df['Salary'] = df['Salary'].abs()

In [150]:
df.describe()

       CustomerID         Age         Salary
count  300.000000  225.000000     152.000000
mean   114.746667   10.746667   38273.750000
std     80.658385   19.774009   36837.249772
min      0.000000   -3.000000   10000.000000
25%     45.750000   -3.000000   10000.000000
50%    101.000000    0.000000   10000.000000
75%    156.250000   25.000000   66370.000000
max    299.000000   59.000000  119613.000000

In [151]:
df.isnull().sum()

CustomerID       0
Name             0
Age             75
Salary         148
City            49
Email            0
JoiningDate     66
dtype: int64

In [152]:
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())

In [153]:
df[(df['Salary'] > 10000) & (df['Salary'] < 25000)]

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
120,120,Aman,0.0,24929.0,Chandigarh,aman19@gmail.com,2023/04/20

In [154]:
df['Salary'].mode()

0    38273.75
Name: Salary, dtype: float64

In [155]:
df['Salary'].value_counts()[lambda x: x == 1]

Salary
116530.0    1
112349.0    1
98172.0     1
86542.0     1
95880.0     1
           ..
54934.0     1
27806.0     1
96810.0     1
63406.0     1
39808.0     1
Name: count, Length: 66, dtype: int64

In [156]:
df['Age']

0       NaN
1      32.0
2       NaN
3      -3.0
4       NaN
       ...
295    -3.0
296    54.0
297     0.0
298     NaN
299     NaN
Name: Age, Length: 300, dtype: float64

In [157]:
df['Age'] = df['Age'].abs()

In [158]:
age_mean = df.loc[df['Age'] >= 20, 'Age'].mean()

In [159]:
age_mean

np.float64(39.621212121212125)

In [160]:
df.loc[(df['Age']>=0) & (df['Age']<20), 'Age'] = age_mean

In [161]:
df['Age'].isna().sum()

np.int64(75)

In [162]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [163]:
df['Age'] = df['Age'].round().astype(int)

In [164]:
df['Age'].value_counts()[lambda x: x > 1]

Age
40    235
59      6
23      5
35      5
39      4
37      4
41      4
27      3
57      3
51      2
21      2
33      2
34      2
49      2
36      2
48      2
Name: count, dtype: int64

In [165]:
df.info(
    
)

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerID   300 non-null    int64
 1   Name         300 non-null    str
 2   Age          300 non-null    int64
 3   Salary       300 non-null    float64
 4   City         251 non-null    str
 5   Email        300 non-null    str
 6   JoiningDate  234 non-null    str
dtypes: float64(1), int64(2), str(4)
memory usage: 16.5 KB

In [166]:
df['City'].value_counts()

City
Chandigarh    59
Delhi         54
Kolkata       47
Bangalore     46
Mumbai        45
Name: count, dtype: int64

In [167]:
city_null = df[df['City'].isnull()]

In [168]:
df.dropna(subset=['City'], inplace=True)

In [169]:
df['Email'].value_counts()[lambda x: x > 1]

Email
anjali43@gmail.com    5
raj11@gmail.com       4
anjali18@gmail.com    3
aman19@gmail.com      3
rohit9@gmail.com      3
priya20@gmail.com     3
riya36@gmail.com      3
simran35@gmail.com    3
priya2@gmail.com      2
anjali15@gmail.com    2
simran43@gmail.com    2
raj13@gmail.com       2
aman33@gmail.com      2
riya6@gmail.com       2
riya24@gmail.com      2
aman48@gmail.com      2
aman44@gmail.com      2
rohit30@gmail.com     2
rohit6@gmail.com      2
aman16@gmail.com      2
simran3@gmail.com     2
rohit38@gmail.com     2
aman46@gmail.com      2
riya45@gmail.com      2
aman28@gmail.com      2
simran18@gmail.com    2
rohit3@gmail.com      2
anjali31@gmail.com    2
simran37@gmail.com    2
rohit7@gmail.com      2
rohit28@gmail.com     2
anjali14@gmail.com    2
simran22@gmail.com    2
riya7@gmail.com       2
riya29@gmail.com      2
karan8@gmail.com      2
aman9@gmail.com       2
aman20@gmail.com      2
anjali40@gmail.com    2
anjali38@gmail.com    2
anjali25@gmail.com    2
rohit22@gmail.com     2
raj4@gmail.com        2
simran25@gmail.com    2
karan29@gmail.com     2
simran30@gmail.com    2
simran16@gmail.com    2
Name: count, dtype: int64

In [170]:
city_null.insert(0, 'sr_no', range(1, len(city_null) + 1))

In [171]:
city_null

,sr_no,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,1,0,riya,40,116530.00,NaN,riya48@gmail.com,2023/04/20
1,2,139,rohit,32,38273.75,NaN,rohit42@gmail.com,15/02/2023
6,3,6,Raj,40,38273.75,NaN,raj21@gmail.com,2023-01-15
11,4,11,Aman,40,86542.00,NaN,aman20@gmail.com,15/02/2023
14,5,102,Anjali,40,38273.75,NaN,anjali20@gmail.com,NaN
18,6,18,Priya,21,10000.00,NaN,priya22@gmail.com,15/02/2023
26,7,34,Karan,59,38273.75,NaN,karan7@gmail.com,2023-01-15
33,8,33,Karan,40,10000.00,NaN,karan35@gmail.com,2023-01-15
36,9,129,rohit,40,106951.00,NaN,rohit20@gmail.com,NaN
37,10,44,Priya,40,10000.00,NaN,priya48@gmail.com,NaN
39,11,39,riya,40,38273.75,NaN,riya20@gmail.com,15/02/2023
40,12,49,aman,57,10000.00,NaN,aman37@gmail.com,NaN
43,13,133,Anjali,40,38273.75,NaN,anjali18@gmail.com,15/02/2023
47,14,47,Simran,49,38273.75,NaN,simran44@gmail.com,NaN
53,15,17,Riya,40,10000.00,NaN,riya24@gmail.com,2023-01-15
71,16,73,Priya,40,10000.00,NaN,priya32@gmail.com,2023/04/20
72,17,118,Aman,38,72976.00,NaN,aman35@gmail.com,2023-01-15
82,18,82,Simran,24,38273.75,NaN,simran20@gmail.com,March 10 2023
88,19,10,priya,40,102345.00,NaN,priya42@gmail.com,NaN
95,20,55,Raj,40,56666.00,NaN,raj24@gmail.com,NaN
101,21,125,Karan,40,10000.00,NaN,karan7@gmail.com,2023-01-15
104,22,104,Rohit,40,38273.75,NaN,rohit31@gmail.com,2023-01-15
115,23,22,karan,40,10000.00,NaN,karan24@gmail.com,2023-01-15
123,24,123,Raj,40,64350.00,NaN,raj42@gmail.com,March 10 2023
125,25,125,rohit,40,10000.00,NaN,rohit22@gmail.com,NaN
137,26,137,Aman,40,38273.75,NaN,aman2@gmail.com,March 10 2023
140,27,73,Karan,40,53202.00,NaN,karan13@gmail.com,2023-01-15
149,28,140,Raj,40,38273.75,NaN,raj5@gmail.com,March 10 2023
154,29,154,Priya,36,38273.75,NaN,priya36@gmail.com,March 10 2023
156,30,156,Karan,44,38273.75,NaN,karan20@gmail.com,NaN
170,31,67,Rohit,40,38273.75,NaN,rohit50@gmail.com,15/02/2023
171,32,125,simran,40,38273.75,NaN,simran46@gmail.com,NaN
174,33,174,karan,40,51779.00,NaN,karan34@gmail.com,2023-01-15
181,34,181,Anjali,37,38273.75,NaN,anjali16@gmail.com,NaN
185,35,185,raj,46,38273.75,NaN,raj38@gmail.com,2023/04/20
189,36,189,Raj,40,38273.75,NaN,raj15@gmail.com,March 10 2023
193,37,56,Priya,40,38273.75,NaN,priya34@gmail.com,March 10 2023
198,38,198,Simran,40,44906.00,NaN,simran49@gmail.com,2023/04/20
223,39,223,Aman,52,38273.75,NaN,aman43@gmail.com,2023/04/20
229,40,50,Rohit,40,71849.00,NaN,rohit40@gmail.com,2023/04/20
243,41,117,Karan,40,62898.00,NaN,karan6@gmail.com,2023-01-15
247,42,59,Priya,40,38273.75,NaN,priya45@gmail.com,2023-01-15
250,43,38,raj,40,38273.75,NaN,raj14@gmail.com,2023/04/20
252,44,252,Priya,59,38273.75,NaN,priya2@gmail.com,2023/04/20
257,45,257,Priya,59,10000.00,NaN,priya16@gmail.com,2023-01-15
259,46,259,Anjali,40,38273.75,NaN,anjali50@gmail.com,2023-01-15
272,47,272,priya,40,87300.00,NaN,priya20@gmail.com,2023-01-15
291,48,291,rohit,40,10000.00,NaN,rohit2@gmail.com,2023/04/20
292,49,292,rohit,40,38273.75,NaN,rohit19@gmail.com,2023-01-15

In [ ]:
city_null['sr_no']

In [182]:
def enter_city(s_no, city):
    if city_null.loc[city_null['sr_no'] == s_no, 'City'].isnull():
        city_null.loc[city_null['sr_no'] == s_no, 'City'] = city
    else:
        print(f"City for sr_no {s_no} is already filled.")

In [ ]:
enter_city(2, 'New York')

In [176]:
city_null[city_null['sr_no'] == 49].dtypes

sr_no            int64
CustomerID       int64
Name               str
Age              int64
Salary         float64
City               str
Email              str
JoiningDate        str
dtype: object

In [194]:
(city_null['City'].isna())

0      False
1       True
6       True
11      True
14      True
18      True
26      True
33      True
36      True
37      True
39      True
40      True
43      True
47      True
53      True
71      True
72      True
82      True
88      True
95      True
101     True
104     True
115     True
123     True
125     True
137     True
140     True
149     True
154     True
156     True
170     True
171     True
174     True
181     True
185     True
189     True
193     True
198     True
223     True
229     True
243     True
247     True
250     True
252     True
257     True
259     True
272     True
291     True
292     True
Name: City, dtype: bool

In [195]:
sr_no = 5
mask = (city_null['sr_no'] == sr_no) & (city_null['City'].isna())
mask

0      False
1      False
6      False
11     False
14      True
18     False
26     False
33     False
36     False
37     False
39     False
40     False
43     False
47     False
53     False
71     False
72     False
82     False
88     False
95     False
101    False
104    False
115    False
123    False
125    False
137    False
140    False
149    False
154    False
156    False
170    False
171    False
174    False
181    False
185    False
189    False
193    False
198    False
223    False
229    False
243    False
247    False
250    False
252    False
257    False
259    False
272    False
291    False
292    False
dtype: bool

In [196]:
def enter_city():
    city = input("Enter a city name: ")
    sr_no = int(input("Enter Serial number: "))
    
    mask = (city_null['sr_no'] == sr_no) & (city_null['City'].isna())
    
    if mask.any():
        city_null.loc[mask, 'City'] = city
        print('city updated successfully ')
    else: 
        print("City already exists or invalid serial number")

In [198]:
city_null.rename(columns={'CustomerID' : 'C_ID'}, inplace= True)

In [200]:
city_null.head(2)

,sr_no,C_ID,Name,Age,Salary,City,Email,JoiningDate
0,1,0,riya,40,116530.00,New York,riya48@gmail.com,2023/04/20
1,2,139,rohit,32,38273.75,NaN,rohit42@gmail.com,15/02/2023

In [201]:
city_null.columns

Index(['sr_no', 'C_ID', 'Name', 'Age', 'Salary', 'City', 'Email',
       'JoiningDate'],
      dtype='str')

In [204]:
city_null['JoiningDate'] = pd .to_datetime(
    city_null['JoiningDate'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
    
)

In [205]:
city_null.head(5)

,sr_no,C_ID,Name,Age,Salary,City,Email,JoiningDate
0,1,0,riya,40,116530.00,New York,riya48@gmail.com,2023-04-20
1,2,139,rohit,32,38273.75,NaN,rohit42@gmail.com,2023-02-15
6,3,6,Raj,40,38273.75,NaN,raj21@gmail.com,2023-01-15
11,4,11,Aman,40,86542.00,NaN,aman20@gmail.com,2023-02-15
14,5,102,Anjali,40,38273.75,NaN,anjali20@gmail.com,NaT

In [217]:
city_null[city_null['Name'] == 'rohit']

     sr_no  C_ID   Name  Age     Salary City              Email JoiningDate
1        2   139  rohit   32   38273.75  NaN  rohit42@gmail.com  2023-02-15
36       9   129  rohit   40  106951.00  NaN  rohit20@gmail.com         NaT
125     25   125  rohit   40   10000.00  NaN  rohit22@gmail.com         NaT
291     48   291  rohit   40   10000.00  NaN   rohit2@gmail.com  2023-04-20
292     49   292  rohit   40   38273.75  NaN  rohit19@gmail.com  2023-01-15

In [212]:
city_null[city_null['Name'].str.contains('rohit')]

     sr_no  C_ID     Name  Age     Salary City              Email JoiningDate
1        2   139   rohit    32   38273.75  NaN  rohit42@gmail.com  2023-02-15
36       9   129    rohit   40  106951.00  NaN  rohit20@gmail.com         NaT
125     25   125    rohit   40   10000.00  NaN  rohit22@gmail.com         NaT
291     48   291   rohit    40   10000.00  NaN   rohit2@gmail.com  2023-04-20
292     49   292   rohit    40   38273.75  NaN  rohit19@gmail.com  2023-01-15

In [215]:
city_null['Name'] = city_null['Name'].str.strip()

In [225]:
new_df = pd.read_csv('check_data.csv')

In [226]:
new_df

             name  age     city
0     ajay sharma   34    delhi
1     pawan kumar   43      chd
2     rajat singh   33   mohali
3  manpreet singh   34  landran
4    lalit panwar   55      chd
5      raja kumar   54    delhi

In [228]:
new_df[['first_name', 'last_name']] = new_df['name'].str.split(' ', expand=True)

In [231]:
new_df = new_df[['first_name', 'last_name','age', 'city']]

In [232]:
new_df

  first_name last_name  age     city
0       ajay    sharma   34    delhi
1      pawan     kumar   43      chd
2      rajat     singh   33   mohali
3   manpreet     singh   34  landran
4      lalit    panwar   55      chd
5       raja     kumar   54    delhi